spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/products?useSSL=false
    username: mysql
    password: mysql
  flyway:
    locations: classpath:db/migration,sql/data