spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory?useSSL=false
    username: mysql
    password: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/