server:
  port: 8002
spring:
  application:
      name: pricing
  profiles:
    active: prod

#eureka:
#  instance:
#    statusPageUrlPath: ${management.context-path}/echo
#    healthCheckUrlPath: ${management.context-path}/echo
#    home-page-url-path: ${management.context-path}/
#    lease-renewal-interval-in-seconds: 10
#  client:
#    healthcheck:
#      enabled: true
#    registryFetchIntervalSeconds: 5