server:
  port: 8000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0